# Generated by Django 5.2.6 on 2025-09-22 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.URLField(blank=True, help_text='Cloudinary URL for profile picture', max_length=500, null=True),
        ),
    ]
